[package]
name = "exemples"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1.47.0"
axum-rh = { path = "../", features = ["base"] }
axum = "0.8.4"
serde = "1.0.219"
serde_json = "1.0.141"
env_logger = "0.11.8"
log.workspace = true
