[package]
name = "exemples"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1.43.0"
axum-rh = { path = "../", features = ["base"] }
axum = "0.8.1"
serde = "1.0.217"
serde_json = "1.0.138"
env_logger = "0.11.6"
