[package]
name = "exemples"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1.44.1"
axum-rh = { path = "../", features = ["base"] }
axum = "0.8.1"
serde = "1.0.219"
serde_json = "1.0.140"
env_logger = "0.11.7"
