[workspace]
resolver = "2"
members = ["axum-rh", "macros", "axum-rh/exemples"]


[workspace.dependencies]
log = { version = "0.4.27", features = ["kv"] }
axum = { version = "0.8.4", features = ["default", "macros"] }
